### ISSUE TITLE
libocsync.so.0: undefined symbol: csync_get_progress_callback

### ISSUE THREAD

**Issue by risacher** [csawyerYumaed/pyOwnCloud#70]
Won't start on Ubuntu 13.04 (raring ringtail).  Is my libocsync0 too old?

```
~$ oclient -h                                                                                
root-DEBUG: Keyring not available                                                                                   
root-DEBUG: ProgressBar not available                                                                               
csync.csynclib.pre-DEBUG: Found ocsync at libocsync.so.0                                                            
Traceback (most recent call last):                                                                                 
  File "/usr/local/bin/oclient", line 9, in <module>                                                                
    load_entry_point('pyOwnCloud==0.4.pre', 'console_scripts', 'oclient')()                                         
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 343, in load_entry_point                           
    return get_distribution(dist).load_entry_point(group, name)                                                     
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2307, in load_entry_point                          
    return ep.load()                                                                                                
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2013, in load                                      
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])                                         
  File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csync.py", line 29, in <module>   
    import csynclib                                                                                                 
  File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csynclib/__init__.py", line 32, in
 <module>                                                                                                           
    from . import post                                                                                              
  File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csynclib/post.py", line 119, in <m
odule>                                                                                                              
    csync_get_progress_callback = csynclib.csync_get_progress_callback                                              
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__                                            
    func = self.__getitem__(name)                                                                                   
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__                                            
    func = self._FuncPtr((name_or_ordinal, self))                                                                   
AttributeError: /usr/lib/x86_64-linux-gnu/libocsync.so.0: undefined symbol: csync_get_progress_callback    

~$ strings /usr/lib/x86_64-linux-gnu/libocsync.so.0 | grep progress_callback                 
csync_set_progress_callback                                                                                         
progress_callback                                                                                                   
csync_set_progress_callback: This function must be called before initialization.                                   
```

**Comment by yavama** [comment]
any news here ??

**Comment by yavama** [comment]
any news here ?? i have the same problem
