### ISSUE TITLE
problem with oclient -h

### ISSUE THREAD

**Issue by yavama** [csawyerYumaed/pyOwnCloud#77]
i've just installed pyOwncloud anc i've got this when runing oclient -h
root-DEBUG: ProgressBar not available
csync.csynclib.pre-DEBUG: Found ocsync at /usr/lib/libocsync.so.0
Traceback (most recent call last):
  File "/usr/local/bin/oclient", line 9, in <module>
    load_entry_point('pyOwnCloud==0.4.pre', 'console_scripts', 'oclient')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csync.py", line 29, in <module>
    import csynclib
  File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csynclib/__init__.py", line 1, in <module>
    from . import pre
  File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csynclib/pre.py", line 25, in <module>
    csynclib = getCSync()
  File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csynclib/pre.py", line 12, in getCSync
    return CDLL('/usr/lib/libocsync.so.0')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libocsync.so.0: wrong ELF class: ELFCLASS64

what's wrong with ? any help plz ?

**Comment by csawyerYumaed** [comment]
From the readme:

!Attention: the recent version of pyOwnCloud doesn't work with the recent versions of ocsync! PyOwnCloud needs a version lower than 0.91.0!

FYI, the official owncloud client includes a command line client now, and may alleviate most use cases for this code: https://doc.owncloud.org/desktop/2.1/advancedusage.html

**Comment by yavama** [comment]
i'm already using a lower version 

what's this command line client ? it replace pyowncloud ??
