### ISSUE TITLE
urlopen error unknown url type: https

### ISSUE THREAD

**Issue by linamu** [csawyerYumaed/pyOwnCloud#79]
Hi @csawyerYumaed,

could you help me with this error ?

Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
Traceback (most recent call last):
  File "./setup.py", line 2, in <module>
    use_setuptools()
  File "/home/dhouha/Bureau/openwrt/build_dir/target-mipsel_r2_uClibc-0.9.32/pyowncloud/distribute_setup.py", line 152, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/dhouha/Bureau/openwrt/build_dir/target-mipsel_r2_uClibc-0.9.32/pyowncloud/distribute_setup.py", line 131, in _do_download
    to_dir, download_delay)
  File "/home/dhouha/Bureau/openwrt/build_dir/target-mipsel_r2_uClibc-0.9.32/pyowncloud/distribute_setup.py", line 201, in download_setuptools
    src = urlopen(url)
  File "/home/dhouha/Bureau/openwrt/staging_dir/target-mipsel_r2_uClibc-0.9.32/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/home/dhouha/Bureau/openwrt/staging_dir/target-mipsel_r2_uClibc-0.9.32/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/home/dhouha/Bureau/openwrt/staging_dir/target-mipsel_r2_uClibc-0.9.32/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/dhouha/Bureau/openwrt/staging_dir/target-mipsel_r2_uClibc-0.9.32/usr/lib/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(*args)
  File "/home/dhouha/Bureau/openwrt/staging_dir/target-mipsel_r2_uClibc-0.9.32/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/home/dhouha/Bureau/openwrt/staging_dir/target-mipsel_r2_uClibc-0.9.32/usr/lib/python2.7/urllib2.py", line 625, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/dhouha/Bureau/openwrt/staging_dir/target-mipsel_r2_uClibc-0.9.32/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/home/dhouha/Bureau/openwrt/staging_dir/target-mipsel_r2_uClibc-0.9.32/usr/lib/python2.7/urllib2.py", line 423, in _open
    'unknown_open', req)
  File "/home/dhouha/Bureau/openwrt/staging_dir/target-mipsel_r2_uClibc-0.9.32/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/home/dhouha/Bureau/openwrt/staging_dir/target-mipsel_r2_uClibc-0.9.32/usr/lib/python2.7/urllib2.py", line 1240, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: https>

**Comment by csawyerYumaed** [comment]
This code is no longer used in production.

FYI, the official owncloud client includes a command line client now, and may alleviate most use cases for this code: https://doc.owncloud.org/desktop/2.1/advancedusage.html
